version: '2'
services:
  web:
    container_name: node_c
    build: .
    command: nodemon server.js -e ejs
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8000"
    links:
      - mongo
  mongo:
    container_name: mongo_c
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
